### ISSUE TITLE
confusing 'ir-installer ospd' arguments

### ISSUE THREAD

**Issue by bregman-arie** [rhosqeauto/InfraRed#171] opened 2016-04-17 07:43 UTC
I wanted to run 'ir-installer ospd' on my openstack-ovb environment, but the required arguments made me confused. These are the required arguments:

product-core-version
product-version
images-task
network-isolation

Two questions/requests:

1. What is difference between product-version and product-core-version? I see it can receive the same values but it's not clear from the description what is the difference between the two. could you please extend the description? also, is it possible to determine the value of one them based on the second argument value?

2. network-isolation description is "The overcloud network isolation type" - I really have no idea what types exist. can you extend the description to include some examples for types? also, does it must to be required? can a default be set?

**Comment by yfried-redhat** [comment] 2016-04-17 08:35
1. `product-version` applies to ospd version. core bits (packstack, nova, neutron, etc...) **of the _undercloud_** will match the default unless specified in `prodcut-core-version`. Overcloud version is currently decided by the default images the ospd downloads, so it's hard-coupled to the ospd version ATM. This is standard `rhos-release` usagae
2. @tkammer @obaranov could you please answer?

**Comment by bregman-arie** [comment] 2016-04-17 09:21
@yfried-redhat sorry but not sure I'm following. 

"product-version applies to ospd version." ->  by ospd you mean undercloud? overcloud? 

"core bits (packstack, nova, neutron, etc...) of the undercloud will match the default unless specified in prodcut-core-version" -> so undercloud version is set by 'product-core-version'?

why isn't there one option to specify version for everything?

Can someone please add the necessary documentation. this is quite confusing...

**Comment by tkammer** [comment] 2016-04-17 09:56
The reason there is no "one flag" for both versions is because from OSP8 we need to support undercloud version 8 and overcloud with 7. (basically install OSP7 overcloud using OSP8 undercloud)
Because of this, we made this specific.
But I do agree that we need to make our documentation better..

**Comment by bregman-arie** [comment] 2016-04-17 10:24
Thanks for the answers. 

In my opinion this issue should be closed after:

1. 'no-isolation' set as the default value for network-isolation
2. better documentation on 'product-version', 'product-core-version' and the relationship between them.

*3. should a default be set for image-task also?

**Comment by fhubik** [comment] 2016-05-03 08:13
Ad 2. - I was also confused about these params as it is not documented, simply:
  --product-version {7,8}
                        The product version
                        Allowed values: { 7, 8 }
  --product-version {7,8}
                        The product version
                        Allowed values: { 7, 8 }
is not enough.

**Comment by fhubik** [comment] 2016-05-06 13:25
Luigi pointed out to another related weird code here. We have in several playbooks code:
```
- name: create necessary repos with for director using rhos-release
  command: "rhos-release {{ installer.product.version }}-director -p {{ installer.product.build }}"
  register: command_result
  until: command_result.stderr.find('Connection reset by peer') == -1
  retries: 40
  delay: 5

- debug:
      msg: "rhos-release {{ installer.product.core.version }}-director -p {{ installer.product.core.build }}"

- name: create necessary repos for core using rhos-release
  command: "rhos-release {{ installer.product.core.version }}-director -p {{ installer.product.core.build }}"
  register: command_result
  until: command_result.stderr.find('Connection reset by peer') == -1
  retries: 40
  delay: 5
```
This doesn't make much sense, as rhos-release is issued two times with params like
rhos-release (7|8)-director -p puddle
rhos-release (7|8)-director -p puddle
and --help says
Product:
  --product-version {7,8}
                        The product version
                        Allowed values: { 7, 8 }
  --product-core-version {7,8}
                        The product core version
                        Allowed values: { 7, 8 }
A) Shouldn't we call it this way
rhos-release (7|8)-director -p puddle
rhos-release (7|8) -p puddle #with core or vice versa
B) Why we have this "create necessary repos with for director using rhos-release" code two times in one playbook, namely:
./playbooks/installer/ospd/virthost.yml
./roles/installer/ospd/undercloud/tasks/setup.yml
?
Shouldn't be task working with "product.version" mentioned only in virthost, and "product.core.version" in undercloud?

**Comment by krcmarik** [comment] 2016-05-25 19:51
I am trying to get Infrared to install NON-latest puddles, so I do not wanna use default build date "latest", I am trying to specify specific build date of previous build of latest, the problem is that director has different build date from core openstack - for example right now I wanna use director with build date 2016-04-18.1 and core openstack with build date 2016-05-13.1. At some point these two builds were marked as latest at the moment. 
The problem is that I am not able to do that - I tried to specify the product-build option to 2016-04-18.1 director build date and product-core-build to 2016-05-13.1 core openstack build date, but I got all the repositories trying to point to location of 2016-05-13.1 build which is okay for core openstack but fails for director. Whatever is in product-core-build will overwrite product-build as pointed out by Filip in previous comment.
This was performed by infrared (from plays pasted by Filip):
19:15:04 cmd: rhos-release 8-director -p 2016-04-18.1 
19:15:04 start: 2016-05-25 15:14:56.658246
19:15:04 end: 2016-05-25 15:15:09.878220
19:15:04 delta: 0:00:13.219974
19:15:04 stdout: 8-director requires the core repo as well, Installing...
19:15:04 Installed: /etc/yum.repos.d/rhos-release-rhel-7.2.repo
19:15:04 Installing wget...
19:15:04 Installed: /etc/yum.repos.d/rhos-release-8-director.repo
19:15:04 Installed: /etc/yum.repos.d/rhos-release-8.repo
19:15:04 # rhos-release 8-director   -p 2016-04-18.1
19:15:04 # rhos-release 8   -p 
and after that:
19:15:13 cmd: rhos-release 8-director -p 2016-05-13.1
19:15:13 start: 2016-05-25 15:15:13.092575
19:15:13 end: 2016-05-25 15:15:15.075770
19:15:13 delta: 0:00:01.983195
19:15:13 stdout: 8-director requires the core repo as well, Installing...
19:15:13 Installed: /etc/yum.repos.d/rhos-release-rhel-7.2.repo
19:15:13 Installed: /etc/yum.repos.d/rhos-release-8-director.repo
19:15:13 Installed: /etc/yum.repos.d/rhos-release-8.repo
19:15:13 # rhos-release 8-director   -p 
19:15:13 # rhos-release 8   -p 2016-05-13.1

This ends up having repos pointing to 2016-05-13.1 build date and pratically it's not possible to install non latest Openstack puddle.

**Comment by fhubik** [comment] 2016-05-26 10:03
Proposed fix https://github.com/rhosqeauto/InfraRed/pull/257

Also as Marian pointed out, rhos-release is not handling deps between core and director, and moreover handles them faulty, pointing them to non-existing repos. This should be BZilled asap as this means nobody can work with non-latest puddles if he doesn't know exact matching core<->director version numbers!

**Closed** 2016-05-26 15:47 UTC
